BEGIN;

CREATE TABLE IF NOT EXISTS auditors (
  id UUID PRIMARY KEY,
  wallet_address TEXT NOT NULL UNIQUE,
  stake NUMERIC(12, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMIT;
